# Generated by Django 2.2.6 on 2019-11-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alumno_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='numero',
            new_name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='modificado',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='website',
        ),
    ]
