# Generated by Django 2.2.6 on 2019-11-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20191102_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='numero',
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
